### ISSUE TITLE
license question?

### ISSUE THREAD

**Issue by kphillisjr** [Artefact2/libxm#13]
I noticed that the license for this repository is [WTFPL](https://en.wikipedia.org/wiki/WTFPL), and was wondering if I could license the code under the combination of [Unlicense](https://en.wikipedia.org/wiki/Unlicense) (also public domain) and [MIT License](https://en.wikipedia.org/wiki/MIT_License). The main reason for this is to hopefully allow for better adoption in a fashion similar to what [Sean Barret's Single File Library's repository](https://github.com/nothings/stb) uses.

**Comment by Artefact2** [comment]
The WTFPL clearly says, do whatever you want.

I doubt switching around the license will improve adoption, this project is very niche in nature.
