### ISSUE TITLE
Buffer overrun in xm_create_context

### ISSUE THREAD

**Issue by nukep** [Artefact2/libxm#6]
I'm writing a [Rust wrapper](https://github.com/nukep/libxm-rs) for `libxm`, and noticed that there's no bounds for `moddata` in `xm_create_context()`. This is obviously bad if `moddata` is corrupted or invalid.

From what it appears, you seem to be aware of this issue already; it's listed in the README as:
* Loading a bogus file (that yet has a valid 60-byte header) will probably result in a segmentation fault.

---
Are there any plans to address this issue in the near future?

**Comment by Artefact2** [comment]
Sure! Do you have ideas for a fix?

**Comment by nukep** [comment]
How about adding a length parameter to `xm_create_context`?
```c
int xm_create_context(xm_context_t**, const char* moddata, size_t moddata_length, uint32_t rate);
```
Adding an additional parameter to an existing function would break the API. Buuutt... we could change it anyway if you're not concerned about backwards compatibility. Otherwise, add something like `xm_create_context_2`?

Basically, by providing a length for `moddata`, we can check that all read offsets are within the bounds of `moddata` and return an error if it's out of bounds. In theory, this should prevent buffer overruns and the segfaults that likely resulted from them.

If you give me the green light, I can attempt a fix and keep you posted. :)

**Comment by Artefact2** [comment]
Sure, go ahead! But don't break the ABI. I suggest you make a `xm_create_context_safe()` function, perhaps. (And you can change `xm_create_context()` to call the safe variant with `INT_MAX` length.)

It will make the load code a LOT more tedious, though.

**Comment by nukep** [comment]
That's fine by me.

**Comment by Artefact2** [comment]
Actually, you could probably do it quickly and reliably by adding a bounds check to the `READ_U8` macro. I believe all our reads in moddata use this.

**Comment by nukep** [comment]
Sure, that's easy. Do you want the macros to assume that `moddata_length` is in scope, or do you want it supplied as a parameter?

**Comment by Artefact2** [comment]
I'm fine with either.
